### ISSUE TITLE
Amstrad 464

### ISSUE THREAD

**Issue by toncho11** [Laci1953/RTM-Z80#4]
Hi,

Would it load on my Amstrad 464 with 64 KB of memory?

Please post some screenshots and a video (no matter which Z80 machine) so people can get the idea of what is it.

**Comment by Laci1953** [comment]
Hi,please consult the manual, you have there detailed info.Ladislau

    On Saturday, January 22, 2022, 12:59:04 PM GMT+2, toncho11 ***@***.***> wrote:  
 
 


Hi,

Would it load on my Amstrad 464 with 64 KB of memory?

Please post some screenshots and a video (no matter which Z80 machine) so people can get the idea of what is it.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by toncho11** [comment]
Thank you for not answering.

**Comment by Laci1953** [comment]
How could I know what exact hardware configuration you have on your "Amstrad 464" ?
RTM-Z80 needs interrupt mode 2.
Plus, you need to set the CTC ports, SIO ports (if you have SIO...).
Again, read the manual, page 98.

**Comment by toncho11** [comment]
You can make a list of hardware you have tried. 
I have no idea what interrupt mode 2 is.

**Comment by Laci1953** [comment]
1. In the RTM/Z80 manual, page 43: when configured accordingly, RTM/Z80 will run on the following environments:
• CP/M running under Z80SIM Z80 simulator
• RC2014, with or without CP/M, using the following configurations:
o SC112 + SC108(Z80 + 32KB SCM EPROM + 2x64KB RAM) + SC110(CTC, SIO) + Digital I/O module
o SC112 + SC108(Z80 + 32KB RTM/Z80 EPROM + 2x64KB RAM) + SC110(CTC, SIO) + Digital I/O module
o SC112 + Karl Brokstad’s Z80 22c module + Memory Module(32KB RTM/Z80 EPROM + 2x64KB RAM) + SC110(CTC, SIO) + Digital I/O module
o SC112 + Karl Brokstad’s Z80 22c module + 512KB RAM/ROM Memory Module + SC110(CTC, SIO) + Digital I/O module
An all other hardware, the I/O ports and interrupt levels must be set "by hand" (see manual, page 98: Porting RTM/Z80 to other hardware)

2. In the ZILOG Z80 User Manual (UM008011-0816), page 186:
The IM 2 instruction sets the vectored Interrupt Mode 2. This mode allows an indirect call
to any memory location by an 8-bit vector supplied from the peripheral device. This vector
then becomes the least-significant eight bits of the indirect pointer, while the I Register in
the CPU provides the most-significant eight bits. This address points to an address in a
vector table that is the starting address for the interrupt service routine.

**Comment by toncho11** [comment]
Some feedback.
I think this project can gain more popularity (if you care about this) if people see this in your home page:

"RTM/Z80 works on number of home brew Z80 computer(s):
 - RC2014 (...)
And simulators:
 - Z80SIM Z80 simulator"

Supporting a famous Z80 computer will add to the popularity. 

There are even some browser supported simulators. For example you can run an 8086 emulator and an OS like ELKS Linux in the user's browser. So people will get excited if they can load and see you OS in action in a few clicks.

**Comment by Laci1953** [comment]
I totally agree. Just made the appropriate updates in the Read.me
